---
- hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - generic
        - debian
        - darwin
        - karabiner
        - flameshot
        - fzf
        - antigen
        - zsh
        - starship
        - vim
        - terraform
        - packer
        - k9s
        - helm
        - havener
        - kubectl
        - go
        - nodejs
        - gohugo
        - migrate
        - kustomize
        - tmux
        - htop
        - zoxide
