---
- hosts: localhost
  connection: local
  vars:
    gohugo_version: 0.105.0
    migrate_version: 4.15.2
    neovim_version: 0.8.0
    ripgrep_version: 13.0.0
    exa_version: 0.10.1
    zoxide_version: 0.8.3
    # languageservers
    marksman_version: 2022-09-13
    terraform_ls_version: 0.29.3
    lua_ls_version: 3.5.6
    # applies only to linux
    kustomize_version: 4.5.7
    nodejs_version: 19
  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - generic
        - debian
        - darwin
        - karabiner
        - flameshot
        - fzf
        - antigen
        - zsh
        - starship
        - vim
        - terraform
        - packer
        - k9s
        - helm
        - havener
        - kubectl
        - go
        - nodejs
        - gohugo
        - migrate
        - kustomize
        - tmux
        - htop
        - zoxide
        - rectangle
        - openvpn-connect
        - insomnia
        - notion
        - keepassxc
        - vscode
        - aldente
        - nextcloud
        - appcleaner
        - inkscape
        - raycast
        - alt-tab
        - figma
        - mysqlworkbench
        - kap
        - vlc
        - discord
        - spotify
        - the-unarchiver
        - iterm2
        - thunderbird
        - firefox
        - chrome
        - drawio
        - microsoft-remote-desktop
        - fira-code
        - atlas
        - dbeaver
        - neovim
        - exa
