---
- hosts: localhost
  connection: local
  tasks:
    - ansible.builtin.include_role:
        name: generic

    - ansible.builtin.include_role:
        name: debian
      when: ansible_os_family == "Debian"

    - ansible.builtin.include_role:
        name: darwin
      when: ansible_os_family == "Darwin"

    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - fzf
        - antigen
        - zsh
        - starship
        - vim
