---
- hosts: localhost
  connection: local
  vars:
    gohugo_version: 0.121.0
    go_version: 1.21.5
    migrate_version: 4.16.2
    neovim_version: 0.9.4
    ripgrep_version: 14.0.3
    eza_version: 0.16.3
    zoxide_version: 0.9.2
    kustomize_version: 5.3.0
    nodejs_version: 20
  tasks:
    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - debian
        - go
        - nodejs
      when: ansible_os_family == "Debian"

    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - arch
      when: ansible_os_family == "Arch Linux"

    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - darwin
        - karabiner
        - flameshot
        - go
        - nodejs
        - openvpn-connect
        - insomnia
        - notion
        - keepassxc
        - vscode
        - aldente
        - nextcloud
        - appcleaner
        - inkscape
        - raycast
        - alt-tab
        - figma
        - mysqlworkbench
        - kap
        - vlc
        - discord
        - spotify
        - the-unarchiver
        - iterm2
        - thunderbird
        - firefox
        - chrome
        - drawio
        - microsoft-remote-desktop
        - fira-code
        - dbeaver
      when: ansible_os_family == "Darwin"

    - ansible.builtin.include_role:
        name: "{{ item }}"
      loop:
        - generic
        - fzf
        - antigen
        - zsh
        - starship
        - vim
        - terraform
        - packer
        - k9s
        - helm
        - havener
        - kubectl
        - gohugo
        - migrate
        - kustomize
        - tmux
        - htop
        - zoxide
        - atlas
        - neovim
        - eza
