---
- block:
    - name: Upgrade system
      become: true
      apt:
        update_cache: true
        upgrade: dist

    - name: Autoremove unused packages
      become: true
      apt:
        autoremove: true

    - name: Install necessary packages
      become: true
      apt:
        pkg:
          - zsh
          - git
          - sshpass
          - ca-certificates
          - curl
          - apt-transport-https
          - gnupg
          - jq
          - python3-pip

    - name: Change shell to zsh
      become: true
      user:
        name: "{{ ansible_user_id }}"
        shell: /bin/zsh
  when: ansible_os_family == "Debian"
