---
- block:
    - name: "Add nodejs v{{ nodejs_version }} repo"
      become: true
      shell: "curl -fsSL https://deb.nodesource.com/setup_{{ nodejs_version }}.x | sudo -E bash -"

    - name: Install nodejs
      become: true
      apt:
        update_cache: true
        pkg:
          - nodejs
  when: ansible_os_family == "Debian"

- block:
    - name: Install nodejs
      community.general.homebrew:
        name: nodejs
  when: ansible_os_family == "Darwin"

- block:
    - name: Install nodejs
      become: true
      community.general.pacman:
        name: "{{ package }}"
      loop:
        - nodejs
        - npm
      loop_control:
        loop_var: package
  when: ansible_os_family == "Archlinux"
