---
- name: Create .config directory
  file:
    path: ~/.config
    state: directory

- name: Create .local/bin directory
  file:
    path: ~/.local/bin
    state: directory
    recurse: true

- name: Set git config
  ansible.builtin.command: git config --global core.editor "nvim"
