---
- block:
    - name: "Download kustomize {{ kustomize_version }} tar file"
      get_url:
        url: "https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2Fv{{ kustomize_version }}/kustomize_v{{ kustomize_version }}_linux_amd64.tar.gz"
        dest: ~/.local/bin/kustomize.tar.gz

    - name: Extract binary from tar file
      shell: tar xfz ~/.local/bin/kustomize.tar.gz -C ~/.local/bin kustomize

    - name: Remove kustomize tar file
      file:
        path: ~/.local/bin/kustomize.tar.gz
        state: absent
  when: ansible_os_family == "Debian"

- block:
    - name: Install kustomize
      community.general.homebrew:
        name: kustomize
  when: ansible_os_family == "Darwin"

- block:
    - name: Install kustomize
      become: true
      community.general.pacman:
        name: kustomize
  when: ansible_os_family == "Arch Linux"
