---
- name: Install packages
  become: true
  community.general.pacman:
    name: "{{ package }}"
  loop:
    - less
    - otf-monaspace-nerd
    - docker
    - firefox
    - curl
    - git
    - zsh
    - unzip
  loop_control:
    loop_var: package

- name: Change shell to zsh
  become: true
  user:
    name: "{{ ansible_user_id }}"
    shell: /usr/bin/zsh
