---
- block:
    - name: Remove golang apt repo
      become: true
      apt_repository:
        repo: ppa:longsleep/golang-backports
        state: absent

    - name: Download go binaries
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        dest: /opt
        src: "https://go.dev/dl/go{{ go_version }}.linux-amd64.tar.gz"

    - name: Create symlinks for go and gofmt
      become: true
      ansible.builtin.file:
        path: "/usr/bin/{{ bin }}"
        src: "/opt/go/bin/{{ bin }}"
        state: link
      loop:
        - go
        - gofmt
      loop_control:
        loop_var: bin
  when: ansible_os_family == "Debian"

- block:
    - name: Install golang
      community.general.homebrew:
        name: golang
  when: ansible_os_family == "Darwin"

- block:
    - name: Install golang
      become: true
      community.general.pacman:
        name: "{{ package }}"
      loop:
        - go
        - gopls
      loop_control:
        loop_var: package
  when: ansible_os_family == "Archlinux"
