---
- block:
    - name: Add golang apt repo
      become: true
      apt_repository:
        repo: ppa:longsleep/golang-backports

    - name: Install golang
      become: true
      apt:
        update_cache: true
        pkg:
          - golang
  when: ansible_os_family == "Debian"

- block:
    - name: Install golang
      community.general.homebrew:
        name: golang
  when: ansible_os_family == "Darwin"
