---
- block:
    - name: Add hashicorp repo key
      become: true
      apt_key:
        url: https://apt.releases.hashicorp.com/gpg

    - name: Add hashicorp repo
      become: true
      apt_repository:
        repo: "deb https://apt.releases.hashicorp.com {{ ansible_distribution_release }} main"

    - name: Install terraform
      become: true
      apt:
        update_cache: true
        pkg:
          - terraform
  when: ansible_os_family == "Debian"

- block:
    - name: Install terraform
      community.general.homebrew:
        name: terraform
  when: ansible_os_family == "Darwin"

- block:
    - name: Install terraform
      become: true
      community.general.pacman:
        name: terraform
  when: ansible_os_family == "Arch Linux"
