---
- block:
    - name: "Download migrate {{ migrate_version }} package"
      get_url:
        url: "https://github.com/golang-migrate/migrate/releases/download/v{{ migrate_version }}/migrate.linux-amd64.deb"
        dest: /tmp

    - name: "Install migrate {{ migrate_version }}"
      become: true
      apt:
        deb: /tmp/migrate.linux-amd64.deb

    - name: Remove migrate install package
      file:
        path: /tmp/migrate.linux-amd64.deb
        state: absent
  when: ansible_os_family == "Debian"

- block:
    - name: "Download migrate {{ migrate_version }} tar file"
      get_url:
        url: "https://github.com/golang-migrate/migrate/releases/download/v{{ migrate_version }}/migrate.darwin-arm64.tar.gz"
        dest: ~/.local/bin/migrate.tar.gz

    - name: Extract binary from tar file
      shell: tar xfz ~/.local/bin/migrate.tar.gz -C ~/.local/bin migrate

    - name: Remove migrate tar file
      file:
        path: ~/.local/bin/migrate.tar.gz
        state: absent
  when: ansible_os_family == "Darwin"
