---
- block:
    - name: Install tmux
      become: true
      apt:
        update_cache: true
        pkg:
          - tmux
  when: ansible_os_family == "Debian"

- block:
    - name: Install tmux
      community.general.homebrew:
        name: tmux
  when: ansible_os_family == "Darwin"

- block:
    - name: Install tmux
      become: true
      community.general.pacman:
        name: tmux
  when: ansible_os_family == "Arch Linux"

- name: Copy tmux config
  copy:
    src: files/.tmux.conf
    dest: ~/.tmux.conf

- name: Create .tmux file in home directory
  file:
    state: directory
    path: ~/.tmux/plugins
    recurse: true

- name: Clone plugin manager
  git:
    repo: https://github.com/tmux-plugins/tpm
    dest: ~/.tmux/plugins/tpm
    depth: "1"
