---
- block:
    - name: Install tmux
      become: true
      apt:
        update_cache: true
        pkg:
          - tmux
  when: ansible_os_family == "Debian"

- block:
    - name: Install tmux
      community.general.homebrew:
        name: tmux
  when: ansible_os_family == "Darwin"

- name: Copy tmux config
  copy:
    src: files/.tmux.conf
    dest: ~/.tmux.conf
