---
- block:
    - name: "Download eza {{ eza_version }} zip"
      get_url:
        url: "https://github.com/eza-community/eza/releases/download/v{{ eza_version }}/eza_x86_64-unknown-linux-gnu.zip"
        dest: ~/.local/bin/eza.zip

    - name: Extra binary from zip
      unarchive:
        extra_opts:
          - -j
        src: ~/.local/bin/eza.zip
        dest: ~/.local/bin

    - name: Remove eza zip
      file:
        path: ~/.local/bin/eza.zip
        state: absent

    - name: Remove exa
      file:
        path: ~/.local/bin/exa
        state: absent
  when: ansible_os_family == "Debian"

- block:
    - name: Install eza
      community.general.homebrew:
        name: eza
        state: latest

    - name: Remove exa
      community.general.homebrew:
        name: exa
        state: absent
  when: ansible_os_family == "Darwin"
