---
- block:
    - name: "Download gohugo {{ gohugo_version }} tar file"
      get_url:
        url: "https://github.com/gohugoio/hugo/releases/download/v{{ gohugo_version }}/hugo_extended_{{ gohugo_version }}_Linux-64bit.tar.gz"
        dest: ~/.local/bin/gohugo.tar.gz

    - name: Extract binary from tar file
      shell: tar xfz ~/.local/bin/gohugo.tar.gz -C ~/.local/bin hugo

    - name: Remove gohugo tar file
      file:
        path: ~/.local/bin/gohugo.tar.gz
        state: absent
  when: ansible_os_family == "Debian"

- block:
    - name: Install hugo
      community.general.homebrew:
        name: hugo
  when: ansible_os_family == "Darwin"

- block:
    - name: Install hugo
      become: true
      community.general.pacman:
        name: hugo
  when: ansible_os_family == "Arch Linux"
