---
- name: Create config directory
  file:
    path: ~/.config/alacritty
    #state: directory
    state: absent
#- name: Load dracula theme
#ansible.builtin.get_url:
#url: https://raw.githubusercontent.com/dracula/alacritty/05faff15c0158712be87d200081633d9f4850a7d/dracula.yml
#dest: ~/.config/alacritty/dracula.yml

#- name: Copy config
#ansible.builtin.copy:
#src: files/alacritty.yml
#dest: ~/.config/alacritty/alacritty.yml

- name: Remove alacritty
  become: true
  community.general.pacman:
    name: alacritty
    state: absent
