---
- name: Install curl
  become: true
  apt:
    pkg:
      - curl
      - unzip
  when: ansible_os_family == "Debian"

- name: Create .config dir
  file:
    dest: ~/.config/nvim
    state: directory
    recurse: true

- name: Copy config files
  copy:
    src: files/
    dest: ~/.config/nvim

- block:
    - name: Download neovim package
      become: true
      get_url:
        url: "https://github.com/neovim/neovim/releases/download/v{{ neovim_version }}/nvim.appimage"
        dest: /usr/sbin/nvim
        mode: +x
  when: ansible_os_family == "Debian"

- block:
    - name: Install neovim
      community.general.homebrew:
        name: neovim
      ignore_errors: true
  when: ansible_os_family == "Darwin"

- block:
    - name: Download ripgrep package
      get_url:
        url: "https://github.com/BurntSushi/ripgrep/releases/download/{{ ripgrep_version }}/ripgrep_{{ ripgrep_version }}_amd64.deb"
        dest: /tmp/ripgrep.deb

    - name: Install ripgrep
      become: true
      apt:
        deb: /tmp/ripgrep.deb
      ignore_errors: true

    - name: Remove ripgrep.deb file
      file:
        path: /tmp/ripgrep.deb
        state: absent
  when: ansible_os_family == "Debian"

- block:
    - name: Install neovim
      become: true
      community.general.pacman:
        name: neovim
  when: ansible_os_family == "Arch Linux"

- block:
    - name: Install ripgrep
      community.general.homebrew:
        name: ripgrep
      ignore_errors: true
  when: ansible_os_family == "Darwin"
